---
name: 🌟 Front-end Submission
description: 'This can be used to submit a front-end'
title: "New front-end: [Name] for [Service]"
assignees: duyfken
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help contribute this frontend to list!
  - type: dropdown
    id: branch
    attributes:
      label: What platform does this front-end run on?
      multiple: false
      options:
        - Web
        - Mobile (Android/iOS)
        - Desktop
    validations:
      required: true
  - type: input
    id: front-end-name
    attributes:
      label: Front-end Name
      description: What is the name of the front-end?
      placeholder: ex. Invidious
    validations:
      required: true
  - type: input
    id: front-end-for
    attributes:
      label: Front-end For
      description: What service the front-end for?
      placeholder: ex. Youtube
    validations:
      required: true
  - type: input
    id: repository-url
    attributes:
      label: Front-end Repository
      description: What is the URL for the front-ends code repository?
      placeholder: ex. https://github.com/iv-org/invidious
    validations:
      required: true
  - type: input
    id: main-instance
    attributes:
      label: Main/Official Instance
      description: What is the URL for main or official instance for this front-end?
      placeholder: ex. https://yewtu.be/
    validations:
      required: true
